function dT = ThermalDyn(t, T0, Settings, Spacecraft, Nodes, Eclipse, Albedo)

% Function to integrate to retrieve the temperature of each defined node at
% the current time step. Note that this implementation is heavily
% mission-dependent, because of the nodes selection.

% ------------------------------------------------------------------------------ %
%
% The current nodes definition is valid for the e.Inspector ESA mission. 
%
% The selected nodes are:
% - the 6 external surfaces
% - the solar panels 4 surfaces
% - the propulsion unit
% - the EPS subsystem
% - the antenna
%
% ------------------------------------------------------------------------------ %

Ts1     = T0(1);
Ts2     = T0(2);
Ts3     = T0(3);
Ts4     = T0(4);
Ts5     = T0(5);
Ts6     = T0(6);
Tsp1    = T0(7);
Tsp2    = T0(8);
Tsp3    = T0(9);
Tsp4    = T0(10);
Tprop   = T0(11);
Teps    = T0(12);
Tant    = T0(13);
Tpl     = T0(14);

%% Compute general variables
F_sc_earth = Spacecraft.orbit.Re^2 / ((Spacecraft.orbit.alt + Spacecraft.orbit.Re)^2);
Resistance = 100; % Contact resistance [m^2K/W]

%% PDE for the first surface
% The thermal connections considered are:
% - conduction with other surfaces
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
% - radiation with internal elements
dTs1 = (1/(Nodes.S1.rho*Nodes.S1.V*Nodes.S1.cv)) * ( ...
        SunRadiation(Nodes.S1.alfa,Nodes.S1.A,Eclipse,Spacecraft.params.cth(1),Settings) + ...
        EarthRadiation(Nodes.S1.alfa,Nodes.S1.emissivity,Nodes.S1.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Ts1,Nodes.S1.emissivity,Nodes.S1.A,Settings) + ...
        Oppenheimer(Ts1,Ts2,Nodes.S1.A,Nodes.S2.A,Nodes.S1.emissivity,Nodes.S2.emissivity,Nodes.S1.F) + ...
        Oppenheimer(Ts1,Ts3,Nodes.S1.A,Nodes.S3.A,Nodes.S1.emissivity,Nodes.S3.emissivity,Nodes.S1.F) + ...
        Oppenheimer(Ts1,Ts4,Nodes.S1.A,Nodes.S4.A,Nodes.S1.emissivity,Nodes.S4.emissivity,Nodes.S1.F) + ...
        Oppenheimer(Ts1,Ts5,Nodes.S1.A,Nodes.S5.A,Nodes.S1.emissivity,Nodes.S5.emissivity,Nodes.S1.F) + ...
        Oppenheimer(Ts1,Ts6,Nodes.S1.A,Nodes.S6.A,Nodes.S1.emissivity,Nodes.S6.emissivity,Nodes.S1.F) + ...
        Oppenheimer(Ts1,Tprop,Nodes.S1.A,Nodes.Prop.A,Nodes.S1.emissivity,Nodes.Prop.emissivity,Nodes.S1.F) + ...
        Oppenheimer(Ts1,Teps,Nodes.S1.A,Nodes.Eps.A,Nodes.S1.emissivity,Nodes.Eps.emissivity,Nodes.S1.F) + ...
        Oppenheimer(Ts1,Tpl,Nodes.S1.A,Nodes.PL.A,Nodes.S1.emissivity,Nodes.PL.emissivity,Nodes.S1.F) - ...
        Conduction(Ts1,Ts2,Nodes.S1.conductivity,Nodes.S1.Ac,Nodes.S1.thickness,Resistance) - ...
        Conduction(Ts1,Ts4,Nodes.S1.conductivity,Nodes.S1.Ac,Nodes.S1.thickness,Resistance) - ...
        Conduction(Ts1,Ts5,Nodes.S1.conductivity,Nodes.S1.Ac,Nodes.S1.thickness,Resistance) - ...
        Conduction(Ts1,Ts6,Nodes.S1.conductivity,Nodes.S1.Ac,Nodes.S1.thickness,Resistance)...
        );


%% PDE for the second surface
% The thermal connections considered are:
% - conduction with other surfaces
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
% - radiation with internal elements
dTs2 = (1/(Nodes.S2.rho*Nodes.S2.V*Nodes.S2.cv)) * ( ...
        SunRadiation(Nodes.S2.alfa,Nodes.S2.A,Eclipse,Spacecraft.params.cth(2),Settings) + ...
        EarthRadiation(Nodes.S2.alfa,Nodes.S2.emissivity,Nodes.S2.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Ts2,Nodes.S2.emissivity,Nodes.S2.A,Settings) + ...
        Oppenheimer(Ts2,Ts1,Nodes.S2.A,Nodes.S1.A,Nodes.S2.emissivity,Nodes.S1.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Ts3,Nodes.S2.A,Nodes.S3.A,Nodes.S2.emissivity,Nodes.S3.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Ts4,Nodes.S2.A,Nodes.S4.A,Nodes.S2.emissivity,Nodes.S4.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Ts5,Nodes.S2.A,Nodes.S5.A,Nodes.S2.emissivity,Nodes.S5.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Ts6,Nodes.S2.A,Nodes.S6.A,Nodes.S2.emissivity,Nodes.S6.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Tsp3,Nodes.S2.A,Nodes.SP3.A,Nodes.S2.emissivity,Nodes.SP3.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Tsp4,Nodes.S2.A,Nodes.SP4.A,Nodes.S2.emissivity,Nodes.SP4.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Tprop,Nodes.S2.A,Nodes.Prop.A,Nodes.S2.emissivity,Nodes.Prop.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Teps,Nodes.S2.A,Nodes.Eps.A,Nodes.S2.emissivity,Nodes.Eps.emissivity,Nodes.S2.F) + ...
        Oppenheimer(Ts2,Tpl,Nodes.S2.A,Nodes.PL.A,Nodes.S2.emissivity,Nodes.PL.emissivity,Nodes.S2.F) - ...
        Conduction(Ts2,Ts1,Nodes.S2.conductivity,Nodes.S2.Ac,Nodes.S2.thickness,Resistance) - ...
        Conduction(Ts2,Ts3,Nodes.S2.conductivity,Nodes.S2.Ac,Nodes.S2.thickness,Resistance) - ...
        Conduction(Ts2,Ts5,Nodes.S2.conductivity,Nodes.S2.Ac,Nodes.S2.thickness,Resistance) - ...
        Conduction(Ts2,Ts6,Nodes.S2.conductivity,Nodes.S2.Ac,Nodes.S2.thickness,Resistance)...
        );


%% PDE for the third surface
% The thermal connections considered are:
% - conduction with other surfaces
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
% - radiation with internal elements
dTs3 = (1/(Nodes.S3.rho*Nodes.S3.V*Nodes.S3.cv)) * ( ...
        SunRadiation(Nodes.S3.alfa,Nodes.S3.A,Eclipse,Spacecraft.params.cth(3),Settings) + ...
        EarthRadiation(Nodes.S3.alfa,Nodes.S3.emissivity,Nodes.S3.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Ts3,Nodes.S3.emissivity,Nodes.S3.A,Settings) + ...
        Oppenheimer(Ts3,Ts1,Nodes.S3.A,Nodes.S1.A,Nodes.S3.emissivity,Nodes.S1.emissivity,Nodes.S3.F) + ...
        Oppenheimer(Ts3,Ts2,Nodes.S3.A,Nodes.S2.A,Nodes.S3.emissivity,Nodes.S2.emissivity,Nodes.S3.F) + ...
        Oppenheimer(Ts3,Ts4,Nodes.S3.A,Nodes.S4.A,Nodes.S3.emissivity,Nodes.S4.emissivity,Nodes.S3.F) + ...
        Oppenheimer(Ts3,Ts5,Nodes.S3.A,Nodes.S5.A,Nodes.S3.emissivity,Nodes.S5.emissivity,Nodes.S3.F) + ...
        Oppenheimer(Ts3,Ts6,Nodes.S3.A,Nodes.S6.A,Nodes.S3.emissivity,Nodes.S6.emissivity,Nodes.S3.F) + ...
        Oppenheimer(Ts3,Tprop,Nodes.S3.A,Nodes.Prop.A,Nodes.S3.emissivity,Nodes.Prop.emissivity,Nodes.S3.F) + ...
        Oppenheimer(Ts3,Teps,Nodes.S3.A,Nodes.Eps.A,Nodes.S3.emissivity,Nodes.Eps.emissivity,Nodes.S3.F) + ...
        Oppenheimer(Ts3,Tpl,Nodes.S3.A,Nodes.PL.A,Nodes.S3.emissivity,Nodes.PL.emissivity,Nodes.S3.F) - ...
        Conduction(Ts3,Ts2,Nodes.S3.conductivity,Nodes.S3.Ac,Nodes.S3.thickness,Resistance) - ...
        Conduction(Ts3,Ts4,Nodes.S3.conductivity,Nodes.S3.Ac,Nodes.S3.thickness,Resistance) - ...
        Conduction(Ts3,Ts5,Nodes.S3.conductivity,Nodes.S3.Ac,Nodes.S3.thickness,Resistance) - ...
        Conduction(Ts3,Ts6,Nodes.S3.conductivity,Nodes.S3.Ac,Nodes.S3.thickness,Resistance)...
        );


%% PDE for the fourth surface
% The thermal connections considered are:
% - conduction with other surfaces
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
% - radiation with internal elements
dTs4 = (1/(Nodes.S4.rho*Nodes.S4.V*Nodes.S4.cv)) * ( ...
        SunRadiation(Nodes.S4.alfa,Nodes.S4.A,Eclipse,Spacecraft.params.cth(4),Settings) + ...
        EarthRadiation(Nodes.S4.alfa,Nodes.S4.emissivity,Nodes.S4.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Ts4,Nodes.S4.emissivity,Nodes.S4.A,Settings) + ...
        Oppenheimer(Ts4,Ts1,Nodes.S4.A,Nodes.S1.A,Nodes.S4.emissivity,Nodes.S1.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Ts2,Nodes.S4.A,Nodes.S2.A,Nodes.S4.emissivity,Nodes.S2.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Ts3,Nodes.S4.A,Nodes.S3.A,Nodes.S4.emissivity,Nodes.S3.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Ts5,Nodes.S4.A,Nodes.S5.A,Nodes.S4.emissivity,Nodes.S5.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Ts6,Nodes.S4.A,Nodes.S6.A,Nodes.S4.emissivity,Nodes.S6.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Tsp1,Nodes.S4.A,Nodes.SP1.A,Nodes.S4.emissivity,Nodes.SP1.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Tsp2,Nodes.S4.A,Nodes.SP2.A,Nodes.S4.emissivity,Nodes.SP2.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Tprop,Nodes.S4.A,Nodes.Prop.A,Nodes.S4.emissivity,Nodes.Prop.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Teps,Nodes.S4.A,Nodes.Eps.A,Nodes.S4.emissivity,Nodes.Eps.emissivity,Nodes.S4.F) + ...
        Oppenheimer(Ts4,Tpl,Nodes.S4.A,Nodes.PL.A,Nodes.S4.emissivity,Nodes.PL.emissivity,Nodes.S4.F) - ...
        Conduction(Ts4,Ts1,Nodes.S4.conductivity,Nodes.S4.Ac,Nodes.S4.thickness,Resistance) - ...
        Conduction(Ts4,Ts3,Nodes.S4.conductivity,Nodes.S4.Ac,Nodes.S4.thickness,Resistance) - ...
        Conduction(Ts4,Ts5,Nodes.S4.conductivity,Nodes.S4.Ac,Nodes.S4.thickness,Resistance) - ...
        Conduction(Ts4,Ts6,Nodes.S4.conductivity,Nodes.S4.Ac,Nodes.S4.thickness,Resistance)...
        );


%% PDE for the fifth surface
% The thermal connections considered are:
% - conduction with other surfaces
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
% - radiation with internal elements
dTs5 = (1/(Nodes.S5.rho*Nodes.S5.V*Nodes.S5.cv)) * ( ...
        SunRadiation(Nodes.S5.alfa,Nodes.S5.A,Eclipse,Spacecraft.params.cth(5),Settings) + ...
        EarthRadiation(Nodes.S5.alfa,Nodes.S5.emissivity,Nodes.S5.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Ts5,Nodes.S5.emissivity,Nodes.S5.A,Settings) + ...
        Oppenheimer(Ts5,Ts1,Nodes.S5.A,Nodes.S1.A,Nodes.S5.emissivity,Nodes.S1.emissivity,Nodes.S5.F) + ...
        Oppenheimer(Ts5,Ts2,Nodes.S5.A,Nodes.S2.A,Nodes.S5.emissivity,Nodes.S2.emissivity,Nodes.S5.F) + ...
        Oppenheimer(Ts5,Ts3,Nodes.S5.A,Nodes.S3.A,Nodes.S5.emissivity,Nodes.S3.emissivity,Nodes.S5.F) + ...
        Oppenheimer(Ts5,Ts4,Nodes.S5.A,Nodes.S4.A,Nodes.S5.emissivity,Nodes.S4.emissivity,Nodes.S5.F) + ...
        Oppenheimer(Ts5,Ts6,Nodes.S5.A,Nodes.S6.A,Nodes.S5.emissivity,Nodes.S6.emissivity,Nodes.S5.F) + ...
        Oppenheimer(Ts5,Tprop,Nodes.S5.A,Nodes.Prop.A,Nodes.S5.emissivity,Nodes.Prop.emissivity,Nodes.S5.F) + ...
        Oppenheimer(Ts5,Teps,Nodes.S5.A,Nodes.Eps.A,Nodes.S5.emissivity,Nodes.Eps.emissivity,Nodes.S5.F) + ...
        Oppenheimer(Ts5,Tpl,Nodes.S5.A,Nodes.PL.A,Nodes.S5.emissivity,Nodes.PL.emissivity,Nodes.S5.F) - ...
        Conduction(Ts5,Ts1,Nodes.S5.conductivity,Nodes.S5.Ac,Nodes.S5.thickness,Resistance) - ...
        Conduction(Ts5,Ts3,Nodes.S5.conductivity,Nodes.S5.Ac,Nodes.S5.thickness,Resistance) - ...
        Conduction(Ts5,Ts2,Nodes.S5.conductivity,Nodes.S5.Ac,Nodes.S5.thickness,Resistance) - ...
        Conduction(Ts5,Ts4,Nodes.S5.conductivity,Nodes.S5.Ac,Nodes.S5.thickness,Resistance)...
        );


%% PDE for the sixth surface
% The thermal connections considered are:
% - conduction with other surfaces
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
% - radiation with internal elements
% - radiation with the antenna
dTs6 = (1/(Nodes.S6.rho*Nodes.S6.V*Nodes.S6.cv)) * ( ...
        SunRadiation(Nodes.S6.alfa,Nodes.S6.A,Eclipse,Spacecraft.params.cth(6),Settings) + ...
        EarthRadiation(Nodes.S6.alfa,Nodes.S6.emissivity,Nodes.S6.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Ts6,Nodes.S6.emissivity,Nodes.S6.A,Settings) + ...
        Oppenheimer(Ts6,Ts1,Nodes.S6.A,Nodes.S1.A,Nodes.S6.emissivity,Nodes.S1.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Ts2,Nodes.S6.A,Nodes.S2.A,Nodes.S6.emissivity,Nodes.S2.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Ts3,Nodes.S6.A,Nodes.S3.A,Nodes.S6.emissivity,Nodes.S3.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Ts4,Nodes.S6.A,Nodes.S4.A,Nodes.S6.emissivity,Nodes.S4.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Ts5,Nodes.S6.A,Nodes.S5.A,Nodes.S6.emissivity,Nodes.S5.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Tprop,Nodes.S6.A,Nodes.Prop.A,Nodes.S6.emissivity,Nodes.Prop.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Teps,Nodes.S6.A,Nodes.Eps.A,Nodes.S6.emissivity,Nodes.Eps.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Tant,Nodes.S6.A,Nodes.Antenna.A,Nodes.S6.emissivity,Nodes.Antenna.emissivity,Nodes.S6.F) + ...
        Oppenheimer(Ts6,Tpl,Nodes.S6.A,Nodes.PL.A,Nodes.S6.emissivity,Nodes.PL.emissivity,Nodes.S6.F) - ...
        Conduction(Ts6,Ts1,Nodes.S6.conductivity,Nodes.S6.Ac,Nodes.S6.thickness,Resistance) - ...
        Conduction(Ts6,Ts3,Nodes.S6.conductivity,Nodes.S6.Ac,Nodes.S6.thickness,Resistance) - ...
        Conduction(Ts6,Ts2,Nodes.S6.conductivity,Nodes.S6.Ac,Nodes.S6.thickness,Resistance) - ...
        Conduction(Ts6,Ts5,Nodes.S6.conductivity,Nodes.S6.Ac,Nodes.S6.thickness,Resistance)...
        );


%% PDE for the first solar panel surface
% The thermal connections considered are:
% - conduction with other surfaces (?)
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
dTsp1 = (1/(Nodes.SP1.rho*Nodes.SP1.V*Nodes.SP1.cv)) * ( ...
        SunRadiation(Nodes.SP1.alfa,Nodes.SP1.A,Eclipse,Spacecraft.params.cth(7),Settings) + ...
        EarthRadiation(Nodes.SP1.alfa,Nodes.SP1.emissivity,Nodes.SP1.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Tsp1,Nodes.SP1.emissivity,Nodes.SP1.A,Settings) + ...
        Oppenheimer(Tsp1,Ts4,Nodes.SP1.A,Nodes.S4.A,Nodes.SP1.emissivity,Nodes.S4.emissivity,Nodes.SP1.F) - ...
        Conduction(Tsp1,Ts4,Nodes.SP1.conductivity,Nodes.SP1.Ac,Nodes.SP1.thickness,Resistance) - ...
        Conduction(Tsp1,Tsp2,Nodes.SP1.conductivity,Nodes.SP1.Ac,Nodes.SP1.thickness,Resistance*0)...
        );


%% PDE for the second solar panel surface
% The thermal connections considered are:
% - conduction with other surfaces (?)
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
dTsp2 = (1/(Nodes.SP2.rho*Nodes.SP2.V*Nodes.SP2.cv)) * ( ...
        SunRadiation(Nodes.SP2.alfa,Nodes.SP2.A,Eclipse,Spacecraft.params.cth(8),Settings) + ...
        EarthRadiation(Nodes.SP2.alfa,Nodes.SP2.emissivity,Nodes.SP2.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Tsp2,Nodes.SP2.emissivity,Nodes.SP2.A,Settings) + ...
        Oppenheimer(Tsp2,Ts4,Nodes.SP2.A,Nodes.S4.A,Nodes.SP2.emissivity,Nodes.S4.emissivity,Nodes.SP2.F) - ...
        Conduction(Tsp2,Ts4,Nodes.SP2.conductivity,Nodes.SP2.Ac,Nodes.SP2.thickness,Resistance) - ...
        Conduction(Tsp2,Tsp1,Nodes.SP2.conductivity,Nodes.SP2.Ac,Nodes.SP2.thickness,Resistance*0)...
        );


%% PDE for the third solar panel surface
% The thermal connections considered are:
% - conduction with other surfaces (?)
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
dTsp3 = (1/(Nodes.SP3.rho*Nodes.SP3.V*Nodes.SP3.cv)) * ( ...
        SunRadiation(Nodes.SP3.alfa,Nodes.SP3.A,Eclipse,Spacecraft.params.cth(9),Settings) + ...
        EarthRadiation(Nodes.SP3.alfa,Nodes.SP3.emissivity,Nodes.SP3.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Tsp3,Nodes.SP3.emissivity,Nodes.SP3.A,Settings) + ...
        Oppenheimer(Tsp3,Ts2,Nodes.SP3.A,Nodes.S2.A,Nodes.SP3.emissivity,Nodes.S2.emissivity,Nodes.SP3.F) - ...
        Conduction(Tsp3,Ts2,Nodes.SP3.conductivity,Nodes.SP3.Ac,Nodes.SP3.thickness,Resistance) - ...
        Conduction(Tsp3,Tsp4,Nodes.SP3.conductivity,Nodes.SP3.Ac,Nodes.SP3.thickness,Resistance*0)...
        );


%% PDE for the fourth solar panel surface
% The thermal connections considered are:
% - conduction with other surfaces (?)
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with other surfaces
% - radiation to deep space
dTsp4 = (1/(Nodes.SP4.rho*Nodes.SP4.V*Nodes.SP4.cv)) * ( ...
        SunRadiation(Nodes.SP4.alfa,Nodes.SP4.A,Eclipse,Spacecraft.params.cth(10),Settings) + ...
        EarthRadiation(Nodes.SP4.alfa,Nodes.SP4.emissivity,Nodes.SP4.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Tsp4,Nodes.SP4.emissivity,Nodes.SP4.A,Settings) + ...
        Oppenheimer(Tsp4,Ts2,Nodes.SP4.A,Nodes.S2.A,Nodes.SP4.emissivity,Nodes.S2.emissivity,Nodes.SP4.F) - ...
        Conduction(Tsp4,Ts2,Nodes.SP4.conductivity,Nodes.SP4.Ac,Nodes.SP4.thickness,Resistance) - ...
        Conduction(Tsp4,Tsp3,Nodes.SP4.conductivity,Nodes.SP4.Ac,Nodes.SP4.thickness,Resistance*0)...
        );


%% PDE for the propulsion unit
% The thermal connections considered are:
% - conduction with mounting surface
% - radiation from the Sun (?)
% - radiation from Albedo (?)
% - radiation from InfraRed (?)
% - radiation with other surfaces
% - radiation to deep space (?)
% - radiation with internal elements
% - internal power generation/dissipation
dTprop = (1/(Nodes.Prop.rho*Nodes.Prop.V*Nodes.Prop.cv)) * ( ...
        SunRadiation(Nodes.Prop.alfa,Nodes.Prop.A,Eclipse,Spacecraft.params.cth(1),Settings) + ...
        EarthRadiation(Nodes.Prop.alfa,Nodes.Prop.emissivity,Nodes.Prop.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Tprop,Nodes.Prop.emissivity,Nodes.Prop.A,Settings) + ...
        Oppenheimer(Tprop,Ts1,Nodes.Prop.A,Nodes.S1.A,Nodes.Prop.emissivity,Nodes.S1.emissivity,Nodes.Prop.F) + ...
        Oppenheimer(Tprop,Ts2,Nodes.Prop.A,Nodes.S2.A,Nodes.Prop.emissivity,Nodes.S2.emissivity,Nodes.Prop.F) + ...
        Oppenheimer(Tprop,Ts3,Nodes.Prop.A,Nodes.S3.A,Nodes.Prop.emissivity,Nodes.S3.emissivity,Nodes.Prop.F) + ...
        Oppenheimer(Tprop,Ts4,Nodes.Prop.A,Nodes.S4.A,Nodes.Prop.emissivity,Nodes.S4.emissivity,Nodes.Prop.F) + ...
        Oppenheimer(Tprop,Ts5,Nodes.Prop.A,Nodes.S5.A,Nodes.Prop.emissivity,Nodes.S5.emissivity,Nodes.Prop.F) + ...
        Oppenheimer(Tprop,Ts6,Nodes.Prop.A,Nodes.S6.A,Nodes.Prop.emissivity,Nodes.S6.emissivity,Nodes.Prop.F) + ...
        Oppenheimer(Tprop,Teps,Nodes.Prop.A,Nodes.Eps.A,Nodes.Prop.emissivity,Nodes.Eps.emissivity,Nodes.Prop.F) + ...
        Oppenheimer(Tprop,Tpl,Nodes.Prop.A,Nodes.PL.A,Nodes.Prop.emissivity,Nodes.PL.emissivity,Nodes.Prop.F) + ...
        Nodes.Prop.Pdiss - ...
        Conduction(Tprop,Ts1,Nodes.Prop.conductivity,Nodes.Prop.Ac,Nodes.Prop.thickness,Resistance) ...
        );


%% PDE for the EPS subsytem
% The thermal connections considered are:
% - conduction with mounting surface
% - radiation with other surfaces
% - radiation with internal elements
% - internal power generation/dissipation
dTeps = (1/(Nodes.Eps.rho*Nodes.Eps.V*Nodes.Eps.cv)) * ( ...
        Oppenheimer(Teps,Ts1,Nodes.Eps.A,Nodes.S1.A,Nodes.Eps.emissivity,Nodes.S1.emissivity,Nodes.Eps.F) + ...
        Oppenheimer(Teps,Ts2,Nodes.Eps.A,Nodes.S2.A,Nodes.Eps.emissivity,Nodes.S2.emissivity,Nodes.Eps.F) + ...
        Oppenheimer(Teps,Ts3,Nodes.Eps.A,Nodes.S3.A,Nodes.Eps.emissivity,Nodes.S3.emissivity,Nodes.Eps.F) + ...
        Oppenheimer(Teps,Ts4,Nodes.Eps.A,Nodes.S4.A,Nodes.Eps.emissivity,Nodes.S4.emissivity,Nodes.Eps.F) + ...
        Oppenheimer(Teps,Ts5,Nodes.Eps.A,Nodes.S5.A,Nodes.Eps.emissivity,Nodes.S5.emissivity,Nodes.Eps.F) + ...
        Oppenheimer(Teps,Ts6,Nodes.Eps.A,Nodes.S6.A,Nodes.Eps.emissivity,Nodes.S6.emissivity,Nodes.Eps.F) + ...
        Oppenheimer(Teps,Tprop,Nodes.Eps.A,Nodes.Prop.A,Nodes.Eps.emissivity,Nodes.Prop.emissivity,Nodes.Eps.F) + ...
        Oppenheimer(Teps,Tpl,Nodes.Eps.A,Nodes.PL.A,Nodes.Eps.emissivity,Nodes.PL.emissivity,Nodes.Eps.F) + ...
        Nodes.Eps.Pdiss - ...
        Conduction(Teps,Ts4,Nodes.Eps.conductivity,Nodes.Eps.Ac,Nodes.Eps.thickness,Resistance) ...
        );


%% PDE for the antenna
% The thermal connections considered are:
% - conduction with mounting surface
% - radiation from the Sun
% - radiation from Albedo
% - radiation from InfraRed
% - radiation with mounting surface
% - radiation to deep space
% - internal power generation/dissipation
dTant = (1/(Nodes.Antenna.rho*Nodes.Antenna.V*Nodes.Antenna.cv)) * ( ...
        SunRadiation(Nodes.Antenna.alfa,Nodes.Antenna.A,Eclipse,Spacecraft.params.cth(6),Settings) + ...
        EarthRadiation(Nodes.Antenna.alfa,Nodes.Antenna.emissivity,Nodes.Antenna.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Tant,Nodes.Antenna.emissivity,Nodes.Antenna.A,Settings) + ...
        Oppenheimer(Tant,Ts6,Nodes.Antenna.A,Nodes.S6.A,Nodes.Antenna.emissivity,Nodes.S6.emissivity,Nodes.Antenna.F) + ...
        Nodes.Antenna.Pdiss - ...
        Conduction(Tant,Ts6,Nodes.Antenna.conductivity,Nodes.Antenna.Ac,Nodes.Antenna.thickness,Resistance)...
        );


%% PDE for the Payload
% The thermal connections considered are:
% - conduction with mounting surface
% - radiation from the Sun (?)
% - radiation from Albedo (?)
% - radiation from InfraRed (?)
% - radiation with other surfaces
% - radiation to deep space (?)
% - radiation with internal elements
% - internal power generation/dissipation
dTpl = (1/(Nodes.PL.rho*Nodes.PL.V*Nodes.PL.cv)) * ( ...
        SunRadiation(Nodes.PL.alfa,Nodes.PL.A,Eclipse,Spacecraft.params.cth(3),Settings) + ...
        EarthRadiation(Nodes.PL.alfa,Nodes.PL.emissivity,Nodes.PL.A,Albedo,F_sc_earth,Settings) - ...
        DeepSpaceRadiation(Tpl,Nodes.PL.emissivity,Nodes.PL.A,Settings) + ...
        Oppenheimer(Tpl,Ts1,Nodes.PL.A,Nodes.S1.A,Nodes.PL.emissivity,Nodes.S1.emissivity,Nodes.PL.F) + ...
        Oppenheimer(Tpl,Ts2,Nodes.PL.A,Nodes.S2.A,Nodes.PL.emissivity,Nodes.S2.emissivity,Nodes.PL.F) + ...
        Oppenheimer(Tpl,Ts3,Nodes.PL.A,Nodes.S3.A,Nodes.PL.emissivity,Nodes.S3.emissivity,Nodes.PL.F) + ...
        Oppenheimer(Tpl,Ts4,Nodes.PL.A,Nodes.S4.A,Nodes.PL.emissivity,Nodes.S4.emissivity,Nodes.PL.F) + ...
        Oppenheimer(Tpl,Ts5,Nodes.PL.A,Nodes.S5.A,Nodes.PL.emissivity,Nodes.S5.emissivity,Nodes.PL.F) + ...
        Oppenheimer(Tpl,Ts6,Nodes.PL.A,Nodes.S6.A,Nodes.PL.emissivity,Nodes.S6.emissivity,Nodes.PL.F) + ...
        Oppenheimer(Tpl,Teps,Nodes.PL.A,Nodes.Eps.A,Nodes.PL.emissivity,Nodes.Eps.emissivity,Nodes.PL.F) + ...
        Oppenheimer(Tpl,Tprop,Nodes.PL.A,Nodes.Prop.A,Nodes.PL.emissivity,Nodes.Prop.emissivity,Nodes.PL.F) + ...
        Nodes.PL.Pdiss - ...
        Conduction(Tpl,Ts3,Nodes.PL.conductivity,Nodes.PL.Ac,Nodes.PL.thickness,Resistance)...
        );


%% Build the thermal state derivative
dT = [dTs1; dTs2; dTs3; dTs4; dTs5; dTs6; dTsp1; dTsp2; dTsp3; dTsp4; dTprop; dTeps; dTant; dTpl];

end

